CONFIG_NCS_SAMPLES_DEFAULTS=y

# UART wymagany przez libzboss.a (nawet bez logów!)
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_GPIO=y

# Zigbee
CONFIG_ZIGBEE_ADD_ON=y
CONFIG_ZIGBEE_APP_UTILS=y
CONFIG_ZIGBEE_ROLE_COORDINATOR=y

CONFIG_HEAP_MEM_POOL_SIZE=2048

# Wyłącz stos IP Zephyra — niepotrzebny
CONFIG_NET_IPV6=n
CONFIG_NET_IP_ADDR_CHECK=n
CONFIG_NET_UDP=n

# Logi przez wirtualny COM po USB
CONFIG_CONSOLE=y # enables generic console subsystem on the microcontroller side 
CONFIG_UART_CONSOLE=y # route that console output through a UART-style driver
CONFIG_USB_DEVICE_STACK=y # enables the chip's ability to act as a USB device
CONFIG_USB_CDC_ACM=y # makes it pretend to be a serial port

# log configuration
CONFIG_LOG=y # turns on the logging
# 3 specifically corresponds to INF severity — this sets the minimum severity shown
CONFIG_LOG_DEFAULT_LEVEL=3
# wykrycie dołączenia urządzenia
CONFIG_ZIGBEE_TC_REJOIN_ENABLED=y

# Shell configuration 
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_PROMPT_UART="zigbee:~$ "

# Work queue configuration
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048